In [260]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler

In [261]:
pd.set_option('display.max_columns', None)

In [262]:
df = pd.read_csv("houses_madrid.csv")
df.head()

,ad_description,ad_last_update,air_conditioner,balcony,bath_num,built_in_wardrobe,chimney,condition,construct_date,energetic_certif,floor,garage,garden,ground_size,heating,house_id,house_type,kitchen,lift,loc_city,loc_district,loc_full,loc_neigh,loc_street,loc_zone,m2_real,m2_useful,obtention_date,orientation,price,reduced_mobility,room_num,storage_room,swimming_pool,terrace,unfurnished
0,"Particular vende piso de 103 m² en Pinto, prov...",Anuncio actualizado el 10 de abril,1,0,1,0,0,segunda mano/buen estado,1976,en trámite,planta 4ª exterior,plaza de garaje incluida en el precio,0,NaN,NaN,83346506,Piso,NaN,1,Pinto,Distrito Parque Europa - Los Pitufos,", Distrito Parque Europa - Los Pitufos , Pint...",NaN,NaN,"Zona sur, Madrid",103,96,2019-04-12,NaN,164900,0,3,0,0,1,NaN
1,"El suelo de la planta superior es de tarima, l...",más de 5 meses sin actualizar,1,0,2,1,0,segunda mano/buen estado,NaN,no indicado,2 plantas,plaza de garaje incluida en el precio,0,NaN,NaN,38939811,Chalet adosado,NaN,NaN,Pinto,Distrito Parque Europa - Los Pitufos,"Calle de la Paz, 7 , Urb. los pitufos , Distr...",Urb. los pitufos,"Calle de la Paz, 7","Zona sur, Madrid",120,NaN,2019-04-12,NaN,370000,0,4,1,0,1,NaN
2,NaN,más de 5 meses sin actualizar,0,0,2,0,0,segunda mano/buen estado,NaN,no indicado,planta 2ª exterior,plaza de garaje incluida en el precio,0,NaN,NaN,29193861,Piso,NaN,1,Pinto,Distrito Puerta Pinto - Valparaíso,"Calle de San Juan, 18 , Distrito Puerta Pinto...","Calle de San Juan, 18",NaN,"Zona sur, Madrid",99,NaN,2019-04-12,NaN,190000,0,3,0,0,0,NaN
3,NaN,más de 5 meses sin actualizar,1,0,3,1,0,segunda mano/buen estado,NaN,NaN,4 plantas,plaza de garaje incluida en el precio,1,NaN,NaN,37200315,Chalet pareado,NaN,NaN,Pinto,Distrito Parque Europa - Los Pitufos,"Calle Suecia, 9 , Urb. Parque Europa , Distri...",Urb. Parque Europa,"Calle Suecia, 9","Zona sur, Madrid",240,215,2019-04-12,"norte, sur",450000,0,4,1,1,1,NaN
4,Parque Europa. Plaza David Martín junto ambula...,más de 5 meses sin actualizar,1,0,2,1,0,segunda mano/buen estado,2000,no indicado,planta 3ª exterior,plaza de garaje incluida en el precio,1,NaN,NaN,1806508,Dúplex,NaN,1,Pinto,Distrito Parque Europa - Los Pitufos,"Avenida Europa, 29 , Distrito Parque Europa -...","Avenida Europa, 29",NaN,"Zona sur, Madrid",169,100,2019-04-12,"sur, este",282000,1,4,1,0,1,NaN

In [263]:
df.dtypes

ad_description       object
ad_last_update       object
air_conditioner      object
balcony              object
bath_num             object
built_in_wardrobe    object
chimney              object
condition            object
construct_date       object
energetic_certif     object
floor                object
garage               object
garden               object
ground_size          object
heating              object
house_id             object
house_type           object
kitchen              object
lift                 object
loc_city             object
loc_district         object
loc_full             object
loc_neigh            object
loc_street           object
loc_zone             object
m2_real              object
m2_useful            object
obtention_date       object
orientation          object
price                object
reduced_mobility     object
room_num             object
storage_room         object
swimming_pool        object
terrace              object
unfurnished          object
dtype: object

In [264]:
# Replace non-numeric values with 0
df['bath_num'] = df['bath_num'].replace(['bath_num', 'sin baños'], 0)

# Convert the column to integer type
df['bath_num'] = df['bath_num'].astype(int)

In [265]:
df["bath_num"] = df["bath_num"].fillna(0)

# Convert the column to integer type
df["bath_num"] = df["bath_num"].astype(int)

In [266]:
non_numeric_values = df[~df['bath_num'].astype(str).str.isdigit()]['bath_num']
print(non_numeric_values)

Series([], Name: bath_num, dtype: int64)

In [267]:
non_numeric_values = df[~df['built_in_wardrobe'].astype(str).str.isdigit()]['built_in_wardrobe']
print(non_numeric_values)

274     built_in_wardrobe
1036    built_in_wardrobe
1388    built_in_wardrobe
2031    built_in_wardrobe
3410    built_in_wardrobe
4530    built_in_wardrobe
5055    built_in_wardrobe
Name: built_in_wardrobe, dtype: object

In [268]:
# Replace non-numeric values with 0
df['built_in_wardrobe'] = df['built_in_wardrobe'].replace(['built_in_wardrobe'], 0)

# Convert the column to integer type
df['built_in_wardrobe'] = df['built_in_wardrobe'].astype(int)

In [269]:
non_numeric_values = df[~df['chimney'].astype(str).str.isdigit()]['chimney']
print(non_numeric_values)

274     chimney
1036    chimney
1388    chimney
2031    chimney
3410    chimney
4530    chimney
5055    chimney
Name: chimney, dtype: object

In [270]:
df['chimney'] = df['chimney'].replace(['chimney'], 0)
df['chimney'] = df['chimney'].astype(int)

df['garden'] = df['garden'].replace(['garden'], 0)
df['garden'] = df['garden'].astype(int)

df['balcony'] = df['balcony'].replace(['balcony'], 0)
df['balcony'] = df['balcony'].astype(int)

df['construct_date'] = df['construct_date'].replace(['construct_date'], 0)
df['construct_date'] = df['construct_date'].astype(float) 

df['kitchen'] = df['kitchen'].replace(['kitchen'], 0)
df['kitchen'] = df['kitchen'].astype(float) 

df['lift'] = df['lift'].replace(['lift'], 0)
df['lift'] = df['lift'].astype(float) 


df['m2_real'] = df['m2_real'].replace(['m2_real'], 0)
df['m2_real'] = df['m2_real'].astype(float) 

df['m2_useful'] = df['m2_useful'].replace(['m2_useful'], 0) 
df['m2_useful'] = df['m2_useful'].astype(float) 


df['reduced_mobility'] = df['reduced_mobility'].replace(['reduced_mobility'], 0)
df['reduced_mobility'] = df['reduced_mobility'].astype(float) 

df['room_num'] = df['room_num'].replace(['room_num', 'sin habitación'], 0)
df['room_num'] = df['room_num'].astype(float) 

df['storage_room'] = df['storage_room'].replace(['storage_room'], 0)
df['storage_room'] = df['storage_room'].astype(float) 

df['swimming_pool'] = df['swimming_pool'].replace(['swimming_pool'], 0)
df['swimming_pool'] = df['swimming_pool'].astype(float) 

df['terrace'] = df['terrace'].replace(['terrace'], 0)
df['terrace'] = df['terrace'].astype(float) 

df['price'] = df['price'].replace(['price'], 0)
df['price'] = df['price'].astype(float)

In [271]:
df

,ad_description,ad_last_update,air_conditioner,balcony,bath_num,built_in_wardrobe,chimney,condition,construct_date,energetic_certif,floor,garage,garden,ground_size,heating,house_id,house_type,kitchen,lift,loc_city,loc_district,loc_full,loc_neigh,loc_street,loc_zone,m2_real,m2_useful,obtention_date,orientation,price,reduced_mobility,room_num,storage_room,swimming_pool,terrace,unfurnished
0,"Particular vende piso de 103 m² en Pinto, prov...",Anuncio actualizado el 10 de abril,1,0,1,0,0,segunda mano/buen estado,1976.0,en trámite,planta 4ª exterior,plaza de garaje incluida en el precio,0,NaN,NaN,83346506,Piso,NaN,1.0,Pinto,Distrito Parque Europa - Los Pitufos,", Distrito Parque Europa - Los Pitufos , Pint...",NaN,NaN,"Zona sur, Madrid",103.0,96.0,2019-04-12,NaN,164900.0,0.0,3.0,0.0,0.0,1.0,NaN
1,"El suelo de la planta superior es de tarima, l...",más de 5 meses sin actualizar,1,0,2,1,0,segunda mano/buen estado,NaN,no indicado,2 plantas,plaza de garaje incluida en el precio,0,NaN,NaN,38939811,Chalet adosado,NaN,NaN,Pinto,Distrito Parque Europa - Los Pitufos,"Calle de la Paz, 7 , Urb. los pitufos , Distr...",Urb. los pitufos,"Calle de la Paz, 7","Zona sur, Madrid",120.0,NaN,2019-04-12,NaN,370000.0,0.0,4.0,1.0,0.0,1.0,NaN
2,NaN,más de 5 meses sin actualizar,0,0,2,0,0,segunda mano/buen estado,NaN,no indicado,planta 2ª exterior,plaza de garaje incluida en el precio,0,NaN,NaN,29193861,Piso,NaN,1.0,Pinto,Distrito Puerta Pinto - Valparaíso,"Calle de San Juan, 18 , Distrito Puerta Pinto...","Calle de San Juan, 18",NaN,"Zona sur, Madrid",99.0,NaN,2019-04-12,NaN,190000.0,0.0,3.0,0.0,0.0,0.0,NaN
3,NaN,más de 5 meses sin actualizar,1,0,3,1,0,segunda mano/buen estado,NaN,NaN,4 plantas,plaza de garaje incluida en el precio,1,NaN,NaN,37200315,Chalet pareado,NaN,NaN,Pinto,Distrito Parque Europa - Los Pitufos,"Calle Suecia, 9 , Urb. Parque Europa , Distri...",Urb. Parque Europa,"Calle Suecia, 9","Zona sur, Madrid",240.0,215.0,2019-04-12,"norte, sur",450000.0,0.0,4.0,1.0,1.0,1.0,NaN
4,Parque Europa. Plaza David Martín junto ambula...,más de 5 meses sin actualizar,1,0,2,1,0,segunda mano/buen estado,2000.0,no indicado,planta 3ª exterior,plaza de garaje incluida en el precio,1,NaN,NaN,1806508,Dúplex,NaN,1.0,Pinto,Distrito Parque Europa - Los Pitufos,"Avenida Europa, 29 , Distrito Parque Europa -...","Avenida Europa, 29",NaN,"Zona sur, Madrid",169.0,100.0,2019-04-12,"sur, este",282000.0,1.0,4.0,1.0,0.0,1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5250,Se vende piso de 100m2 a reformar en una de la...,Anuncio actualizado el 10 de abril,0,0,3,1,0,segunda mano/para reformar,NaN,en trámite,planta 3ª interior,NaN,0,NaN,NaN,85015449,Piso,NaN,1.0,Madrid,Distrito Salamanca,"DIEGO DE LEON , Barrio Lista , Distrito Salam...",Barrio Lista,DIEGO DE LEON,"Madrid capital, Madrid",115.0,100.0,2019-04-12,"norte, este",715000.0,0.0,3.0,1.0,1.0,1.0,NaN
5251,Estupendo piso de 246 m2 construidos - 44 de z...,Anuncio actualizado el 1 de abril,0,0,3,0,0,segunda mano/para reformar,1948.0,NaN,planta 1ª exterior,plaza de garaje por 50.000 eur adicionales,0,NaN,calefacción central,84235256,Piso,NaN,1.0,Madrid,Distrito Salamanca,"Calle del General Pardiñas, Madrid, 74 , Barr...",Barrio Lista,"Calle del General Pardiñas, Madrid, 74","Madrid capital, Madrid",246.0,206.0,2019-04-12,oeste,1090000.0,0.0,4.0,0.0,0.0,0.0,NaN
5252,Superficie construida: 155 m² (según catastro)...,Anuncio actualizado el 22 de marzo,0,0,3,0,0,segunda mano/para reformar,NaN,en trámite,planta 5ª exterior,NaN,0,NaN,NaN,84752402,Piso,NaN,1.0,Madrid,Distrito Salamanca,", Barrio Lista , Distrito Salamanca , Madrid ...",Barrio Lista,NaN,"Madrid capital, Madrid",155.0,NaN,2019-04-12,NaN,760000.0,0.0,3.0,0.0,0.0,1.0,NaN
5253,"Piso exterior en buen estado.,Piso exterior mu...",Anuncio actualizado el 11 de abril,1,1,2,1,0,segunda mano/buen estado,1940.0,NaN,planta 1ª exterior,NaN,0,NaN,calefacción individual: gas natural,84914185,Piso,NaN,1.0,Madrid,Distrito Salamanca,"Calle de Don Ramón de la Cruz, Madrid , Barri...",Barrio Lista,"Calle de Don Ramón de la Cruz, Madrid","Madrid capital, Madrid",125.0,112.0,2019-04-12,sur,730000.0,0.0,3.0,0.0,0.0,0.0,NaN
5254,"Piso de 216 m2 de los cuales 195 son útiles, e...",Anuncio actualizado el 12 de abril,1,1,3,0,0,segunda mano/para reformar,1949.0,NaN,planta 2ª exterior,NaN,0,NaN,calefacción central,84800977,Piso,NaN,1.0,Madrid,Distrito Salamanca,"Calle de Francisco Silvela, Madrid, 71 , Barr...",Barrio Lista,"Calle de Francisco Silvela, Madrid, 71","Madrid capital, Madrid",216.0,195.0,2019-04-12,"este, oeste",930000.0,1.0,4.0,0.0,0.0,0.0,NaN

In [272]:
df = df.drop(["ad_description", "ad_last_update", "condition", "energetic_certif", "floor", 
            "garage", "loc_district", "loc_full", "loc_neigh", "loc_street", "loc_zone", "orientation",
            "house_type", "obtention_date", "air_conditioner", "house_id", "loc_city", "ground_size", 
            "heating", "unfurnished", "kitchen"], axis=1)

In [273]:
df = df.dropna()

In [274]:
y = df["price"]
df = df.drop("price", axis=1)

In [275]:
df = df.dropna()

In [276]:
X = df
print(X.shape)
X

(1112, 14)

,balcony,bath_num,built_in_wardrobe,chimney,construct_date,garden,lift,m2_real,m2_useful,reduced_mobility,room_num,storage_room,swimming_pool,terrace
0,0,1,0,0,1976.0,0,1.0,103.0,96.0,0.0,3.0,0.0,0.0,1.0
4,0,2,1,0,2000.0,1,1.0,169.0,100.0,1.0,4.0,1.0,0.0,1.0
34,0,2,1,0,2000.0,1,1.0,90.0,70.0,1.0,2.0,0.0,1.0,1.0
36,0,1,1,0,2004.0,1,1.0,82.0,69.0,1.0,2.0,1.0,1.0,1.0
44,0,1,1,0,1983.0,0,0.0,87.0,76.0,0.0,3.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5248,0,2,1,0,1944.0,0,1.0,125.0,100.0,0.0,3.0,0.0,0.0,0.0
5249,0,1,1,0,1930.0,0,1.0,46.0,38.0,0.0,0.0,0.0,0.0,0.0
5251,0,3,0,0,1948.0,0,1.0,246.0,206.0,0.0,4.0,0.0,0.0,0.0
5253,1,2,1,0,1940.0,0,1.0,125.0,112.0,0.0,3.0,0.0,0.0,0.0
5254,1,3,0,0,1949.0,0,1.0,216.0,195.0,1.0,4.0,0.0,0.0,0.0

In [277]:
scaler = StandardScaler() 
  
# transform data 
X = scaler.fit_transform(X) 
y = scaler.fit_transform(y)

ValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.

In [ ]:
reg = LinearRegression().fit(X, y)
reg.score(X, y)

0.6262012275838424